###INDEX BUILDING OPTIONS###

# Create annotations and index files
genome_name: dmel_628
spike_name: elex
index_name: dmel_628_elex

#https://www.ensembl.org/info/data/ftp/index.html
genome_fasta_address: ftp://ftp.ensembl.org/pub/release-99/fasta/drosophila_melanogaster/dna/Drosophila_melanogaster.BDGP6.28.dna.toplevel.fa.gz
genome_gtf_address: ftp://ftp.ensembl.org/pub/release-99/gtf/drosophila_melanogaster/Drosophila_melanogaster.BDGP6.28.99.gtf.gz
cdna_fasta_address: ftp://ftp.ensembl.org/pub/release-99/fasta/drosophila_melanogaster/cdna/Drosophila_melanogaster.BDGP6.28.cdna.all.fa.gz
ncrna_fasta_address: ftp://ftp.ensembl.org/pub/release-99/fasta/drosophila_melanogaster/ncrna/Drosophila_melanogaster.BDGP6.28.ncrna.fa.gz
sirv_zip_address: https://www.lexogen.com/wp-content/uploads/2018/08/SIRV_Set1_Sequences_170612a-ZIP.zip
ercc_fasta_address: https://www-s.nist.gov/srmors/certificates/documents/SRM2374_putative_T7_products_NoPolyA_v2.FASTA

include_sirvs: True
include_erccs: True

#If only using a subset of the ERCCs list here. If empty and include_erccs, then include all
ercc_subset:
  - ERCC-00057
  - ERCC-00073
  - ERCC-00077
  - ERCC-00104
  - ERCC-00112
  - ERCC-00142
  - ERCC-00150
  - ERCC-00162
  - ERCC-00165
  - ERCC-00168

build_star_params:
  genomeSAsparseD: 4
  genomeSAindexNbases: 10
  limitGenomeGenerateRAM: 12000000000

#specify the number of flanking nts to add to each side of the intron.
#Some defaults 30, other source suggests read length - 1:
intron_flanking_nt: 30
